pragma solidity ^0.6.0;

interface AToken {
  /**
   * @dev calculates the balance of the user, which is the
   * principal balance + interest generated by the principal balance +
   * interest generated by the redirected balance
   * @param _user the user for which the balance is being calculated
   * @return the total balance of the user
   **/
  function balanceOf(address _user) external view returns (uint256);

  function redeem(uint256 _amount) external;
}
